#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	- z0mbi3
#	- https://github.com/gh0stzk/dotfiles
#	- z0mbi3.zk@protonmail.com
#

read -r RICETHEME < $HOME/.config/bspwm/.rice
export RICETHEME
PATH="$HOME/.config/bspwm/scripts:$PATH"
rice_dir="$HOME/.config/bspwm/rices/$RICETHEME"

export KWIN_X11_NO_SYNC_TO_VBLANK=1
export KWIN_X11_REFRESH_RATE=144000

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

	# Default 1 monitor with 6 workspaces
	for monitor in "$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)"; do
		bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6' '7' '8'
		#bspc monitor "$monitor" -d '' '' '' '' '' ''
	done

	## For two or three monitors configuration see https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command $HOME/.config/bspwm/scripts/ExternalRules

bspc config window_gap					6
bspc config split_ratio					0.51
bspc config single_monocle				true
bspc config borderless_monocle			false
bspc config gapless_monocle				false

bspc config focus_follows_pointer		true
bspc config pointer_follows_focus		false
bspc config pointer_motion_interval		5
bspc config pointer_modifier			mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner

#BSPWM configuration
bspc config border_radius       8
bspc config border_width         0
bspc config window_gap           10 
bspc config top_padding          30
bspc config bottom_padding       0
bspc config left_padding         0 
bspc config right_padding        0
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true




#bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on
bspc rule -a feh sticky=on state=floating focus=on
bspc rule -a iwgtk state=floating
bspc rule -a mpv desktop=^7
bspc rule -a Localsend_app desktop=^6 state=tiled

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║ 
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

# Set system vars for polybar
. SetSysVars

# Terminate already running polybar, stalonetray, sxhkd and dunst instances
processes=("eww.*bar" "polybar" "sxhkd" "dunst" "stalonetray")

	for process in "${processes[@]}"; do
		if pgrep -f "$process"; then
			pkill -9 -f "$process" > /dev/null; sleep 0.1
		fi
	done

# Load bspwm conf, colors, dunst, bars and/or eww widgets
. ${rice_dir}/Theme.sh

# Launch picom // If you have old hardware or encounter problems 
# uncomment the picom "--legacy-backends" line and comment the current one.
pidof -q picom || { picom --config $HOME/.config/bspwm/picom.conf --no-vsync & }
#pidof -q picom || { picom --legacy-backends --config $HOME/.config/bspwm/picom.conf & }

# Set random wallpaper for actual rice
# while true ; do
# 	feh --randomize --bg-fill ${rice_dir}/walls
# 	sleep 5
# done &
# Launch eww daemon
	feh --randomize --bg-fill ${rice_dir}/walls
pidof -q eww || { eww -c $HOME/.config/bspwm/eww daemon & }

# Reload sxhkd daemon
sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# Launch dunst notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# Launch stalonetray
[[ "$RICETHEME" != "z0mbi3" ]] && stalonetray -c $HOME/.config/bspwm/stalonetrayrc & sleep 0.1 && xdo hide -N stalonetray && touch "/tmp/syshide.lock"

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor
xsetroot -cursor_name left_ptr

nm-applet &
blueberry-tray &
node  ~/.config/local-server/local-cloudflare-api/index.js&
npm run --prefix ~/Downloads/Projects/surfingkeys-conf gulp serve&
greenclip daemon &
pkill localsend
localsend&

#Git pull
cd ~/.config/nvim && git pull

